### ISSUE TITLE
Torch interface?

### ISSUE THREAD

**Issue by ghost** [jcjohnson/cnn-vis#1]
Hi there,

any chance of providing an example of getting your repo to work with Torch? Maybe using the https://github.com/szagoruyko/torch-caffe-binding … might work?

Cheers,

Aj

**Comment by jcjohnson** [comment]
Hi Aj,

I think that getting this to work in Torch would require a pretty substantial rewrite - I'm only using Caffe to compute forward / backward in the network, and all of the optimization, regularization, and resizing logic is all in Python.

Using torch-caffe-binding would let you call the Caffe net from Lua, but you'd then have to reimplement all of the optimization and regularization logic in Torch. Doable, but nontrivial.

Maybe another option would be to use 

https://github.com/facebook/fblualib/blob/master/fblualib/python/README.md

to call cnn-vis directly from Lua? I've never used it before so I don't know if it would work.
